name: cosmic_jump
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flame_tiled: ^1.20.2
  flutter:
    sdk: flutter
  jenny: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7

icons_launcher:
  image_path: assets/images/launcher_icon.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    web:
      enable: true

flutter:
  assets:
    - assets/audio/
    - assets/tiles/
    - assets/images/Asteroids/
    - assets/images/Characters/
    - assets/images/Characters/Mask Dude/
    - assets/images/Characters/Ninja Frog/
    - assets/images/Characters/Pink Man/
    - assets/images/Characters/Virtual Guy/
    - assets/images/Fogs/
    - assets/images/HUD/
    - assets/images/Fogs/
    - assets/images/Traps/Saw/
    - assets/images/Items/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Planets/
    - assets/images/Planets/Pictures/
    - assets/images/Terrain/
    - assets/images/Traps/Saw/
    - assets/tiles/
    - assets/yarn/
