name: cosmic_jump
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  circle_list: ^1.0.5
  dotted_line: ^3.2.2
  flame: ^1.18.0
  flame_audio: ^2.10.2
  flame_tiled: ^1.20.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  jenny: ^1.3.1
  leap:
    git:
      url: https://github.com/ricardodalarme/leap
      ref: 8bbe7b856a908f9906cfb27c849aa146e044b47f
      path: packages/leap
  toggle_switch: ^2.3.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.7

icons_launcher:
  image_path: assets/images/launcher_icon.png
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/Asteroids/
    - assets/images/Backgrounds/
    - assets/images/Characters/
    - assets/images/Characters/Mask Dude/
    - assets/images/Characters/Ninja Frog/
    - assets/images/Characters/Pink Man/
    - assets/images/Characters/Virtual Guy/
    - assets/images/Fogs/
    - assets/images/Fogs/
    - assets/images/HUD/
    - assets/images/Items/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Planets/
    - assets/images/Planets/Pictures/
    - assets/images/Platforms/
    - assets/images/Terrain/
    - assets/images/Traps/Spikes/
    - assets/svgs/
    - assets/tiles/
    - assets/tiles/
    - assets/yarn/
